<?php
//add.phtml

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
	$form->setAttribute('action', $this->url('album', array('action' => 'add')));
	$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo "<div class='form-group'>";
echo $this->formRow($form->get('title')->setAttribute('class', 'form-control'));
echo "</div>";
echo "<div class='form-group'>";
echo $this->formRow($form->get('artist')->setAttribute('class', 'form-control'));
echo "</div>";
echo "<div>";
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
echo "  <a href=" . $this->url('album', array('action' => 'index')) . " class='btn btn-default'>Cancel</a>";
echo "</div>";

//this line can replace above lines, but it lacks the extra styling
//echo $this->formCollection($form);
echo $this->form()->closeTag();
